<MenuScreen>:
    BoxLayout:
        orientation: "vertical"

        ClickableImage:
            source: 'ui/assets/images/arrow_back.png'
            size_hint: None, None
            size: 100, 100
            pos_hint: {'x': 0.01, 'top': 1.1}
            on_release:
                app.root.transition.direction = 'right'
                app.root.current = 'home'

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            FloatLayout:
                size_hint_y: None
                height: 800

                ClickableImage:
                    source: 'ui/assets/images/options_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.14, 'top': 1}
                
                ClickableImage:
                    source: 'assets/images/dev_var_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.48, 'top': 0.875}
                    on_release:
                        app.root.transition.direction = 'left'
                        app.root.current = 'dev_var'

                ClickableImage:
                    source: 'assets/images/empty_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.14, 'top': 0.75}
                
                ClickableImage:
                    source: 'assets/images/empty_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.48, 'top': 0.625}
                
                ClickableImage:
                    source: 'assets/images/empty_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.14, 'top': 0.5}

                ClickableImage:
                    source: 'assets/images/empty_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.48, 'top': 0.375}
                
                ClickableImage:
                    source: 'assets/images/empty_button.png'
                    size_hint: None, None
                    size: 200, 200
                    pos_hint: {'x': 0.14, 'top': 0.25}
